name: eBurger Static Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      # only required for workflows in private repositories
      # actions: read
      # contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true' # change to 'recursive' if needed
      
      - name: Run eburger
        id: eburger
        uses: forefy/eburger-action@main # @main is recommended, although for improved stability change to the latest marketplace release (e.g. v.1.0.1)
  
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.eburger.outputs.sarif }}